# Vim-like navigation for MPV

# Navigation (Seek)
l seek  5
h seek -5
Shift+l seek  60
Shift+h seek -60

# Volume
k add volume 2
j add volume -2

# Playback Speed (Like YouTube usually)
> add speed 0.1
< add speed -0.1

# Quit
q quit
Q quit-watch-later

# Playlist navigation
Shift+n playlist-next
Shift+p playlist-prev

# Toggle OSD
o no-osd cycle-values osd-level 3 1

# Screenshot
s screenshot
S screenshot video
