# High Quality Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=7 # 0-9, 7 is a good balance
screenshot-directory=~/Pictures/mpv-shots
screenshot-template="%F-%P" # Filename: VideoName-TimeStamp
