[manager]
prepend_keymap = [
    # Hardened Commands
    { on = "<A-r>", run = "rename --cursor=before_ext", desc = "Rename" },
    { on = "<A-a>", run = "create", desc = "Create" },
    { on = "<A-f>", run = "filter --smart", desc = "Filter" },
    { on = "<A-/>", run = "find --smart", desc = "Find" },
    { on = "<A-?>", run = "find --previous --smart", desc = "Find (Prev)" },
    { on = "<A-;>", run = "shell --interactive", desc = "Shell" },
    { on = "<A-:>", run = "shell --block --interactive", desc = "Shell (Block)" },
    { on = "<A-s>", run = "search --via=fd", desc = "Search (fd)" },
    { on = "<A-S>", run = "search --via=rg", desc = "Search (rg)" },
    { on = "<A-t>", run = "tab_create --current", desc = "New Tab" },
    { on = "<A-w>", run = "tasks:show", desc = "Tasks" },
    { on = "<A-z>", run = "plugin fzf", desc = "FZF" },
    { on = "<A-Z>", run = "plugin zoxide", desc = "Zoxide" },
    { on = "<A-q>", run = "quit", desc = "Quit (Alt)" },

    # Chords
    { on = [ "<A-g>", "h" ], run = "cd ~", desc = "Go Home" },
    { on = [ "<A-g>", "c" ], run = "cd ~/.config", desc = "Go Config" },
    { on = [ "<A-c>", "c" ], run = "copy path", desc = "Copy Path" },
    { on = [ "<A-m>", "s" ], run = "linemode size", desc = "Linemode Size" },
    { on = [ "<A-,>", "m" ], run = "sort mtime", desc = "Sort Mtime" },

    # Custom Behavior
    { on = "<Space>", run = [ "toggle", "arrow next" ], desc = "Toggle selection" },
]
