# Yazi Configuration (User Override)

[mgr]
show_hidden = true
show_symlink = true

[opener]
book = [
    { run = 'open -a Books "$@"', orphan = true, desc = "Apple Books" }
]

[open]
prepend_rules = [
    { name = "*.epub", use = "book" }
]

[status]
separator_open  = ""
separator_close = ""
show_right = ["permissions", "percentage", "position", "timestamp", "size"]
