# None — plain terminal, no theme/accent colors (standard xterm 16-color palette)
foreground              #e5e5e5
background              #000000
selection_foreground    #000000
selection_background    #7f7f7f
cursor                  #e5e5e5
cursor_text_color       #000000
url_color               #7f7f7f
active_border_color     #7f7f7f
inactive_border_color   #3c3c3c
bell_border_color       #7f7f7f
wayland_titlebar_color system
macos_titlebar_color system
mark1_foreground #000000
mark1_background #7f7f7f
mark2_foreground #000000
mark2_background #7f7f7f
mark3_foreground #000000
mark3_background #7f7f7f

color0  #000000
color8  #7f7f7f
color1  #cd0000
color9  #ff0000
color2  #00cd00
color10 #00ff00
color3  #cdcd00
color11 #ffff00
color4  #0000ee
color12 #5c5cff
color5  #cd00cd
color13 #ff00ff
color6  #00cdcd
color14 #00ffff
color7  #e5e5e5
color15 #ffffff
