# Tokyo Night Storm Kitty Theme
foreground              #a9b1d6
background              #24283b
selection_foreground    #a9b1d6
selection_background    #343b58
cursor                  #c0caf5
cursor_text_color       #24283b
url_color               #73daca
active_border_color     #7aa2f7
inactive_border_color   #292e42
bell_border_color       #e0af68
wayland_titlebar_color system
macos_titlebar_color system
mark1_foreground #24283b
mark1_background #7aa2f7
mark2_foreground #24283b
mark2_background #bb9af7
mark3_foreground #24283b
mark3_background #7dcfff

color0 #414868
color8 #565f89
color1 #f7768e
color9 #f7768e
color2  #9ece6a
color10 #9ece6a
color3  #e0af68
color11 #e0af68
color4  #7aa2f7
color12 #7aa2f7
color5  #bb9af7
color13 #bb9af7
color6  #7dcfff
color14 #7dcfff
color7  #a9b1d6
color15 #c0caf5
