# --- Default Kitty Session ---

# Set initial layout
layout splits

# Tab 1: Editor
new_tab Editor
cd ~
launch nu -c "nvim"

# Tab 2: Shell
new_tab Shell
cd ~
launch nu
# Create a split
launch --location=vsplit nu
